const FOOTBALL_ROLES = {

CLUB_ADMIN:"CLUB_ADMIN",
COACH:"COACH",
ASSISTANT_COACH:"ASSISTANT_COACH",
FITNESS_COACH:"FITNESS_COACH",
TEAM_MANAGER:"TEAM_MANAGER",
DOCTOR:"DOCTOR",
PHYSIOTHERAPIST:"PHYSIOTHERAPIST",
SCOUT:"SCOUT",
PLAYER:"PLAYER",
FAN: "FAN",

};


module.exports=FOOTBALL_ROLES;