const STATUS = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",

  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",

  INVITED: "INVITED",
  EXPIRED: "EXPIRED",

  SUSPENDED: "SUSPENDED",
  LEFT: "LEFT",

  DRAFT: "DRAFT",

  ARCHIVED: "ARCHIVED",

  CANCELLED: "CANCELLED",
};

module.exports = STATUS;