const SUBSCRIPTION_STATUS = {
  TRIAL: "TRIAL",
  PENDING: "PENDING",
  ACTIVE: "ACTIVE",
  EXPIRED: "EXPIRED",
  CANCELLED: "CANCELLED",
  SUSPENDED: "SUSPENDED",
};

module.exports = SUBSCRIPTION_STATUS;