const TOKEN_TYPE = {
  ACCESS: "ACCESS",
  REFRESH: "REFRESH",
  EMAIL_VERIFICATION: "EMAIL_VERIFICATION",
  PASSWORD_RESET: "PASSWORD_RESET",
  INVITATION: "INVITATION",
};

module.exports = TOKEN_TYPE;